### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by n0toose** [HaikuArchives/Fortuna#7]
Hey, I was curious about the licensing of Fortuna, having contributed to it a few months ago.

According to its [HaikuPorts recipe](https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/haiku-apps/fortuna/fortuna-1.0.0.recipe), it is licensed under the MIT license, but the repository doesn't really seem to reflect that.

I was wondering whether this is the case, and if so, I'm wondering whether the repository can be updated accordingly, since I can't reach the original author.

**Comment by humdingerb** [comment]
[Licensing of _Fortuna_ 20200511010548 Jon Yoder.txt](https://github.com/HaikuArchives/Fortuna/files/4610640/Licensing.of._Fortuna_.20200511010548.Jon.Yoder.txt)

Jon confirms the MIT license:

> Anyway, you are correct... Fortuna is MIT. You can assume that if a license isn't specified for code I've written that it's MIT licensed.

**Comment by n0toose** [comment]
Sorry to be a bother, but I see that the names in the license match the ones in the HaikuPorts recipe. Is that certainly correct?

**Comment by humdingerb** [comment]
I don't quite understand... the name of the license (MIT) matches the license in the recipe (MIT). What's the problem?

**Comment by n0toose** [comment]
@humdingerb I'm not sure whether the license in the recipe was correct in the first place-- Did the original author give the rights to the Haiku Software Archives, or should their name be used instead?

**Comment by humdingerb** [comment]
As I wrote above: "Jon confirms the MIT license:"

**Comment by scottmc** [comment]
I think we should list both the original author and Haiku Archives Team as
they've picked up the maintenance.  I don't think MIT is the issue, just
who to credit.  I'd list Darkwyrm first and then the others.

**Comment by humdingerb** [comment]
Alright. That would be for another ticket, to use a BAboutWindow listing DarkWyrm as original author and then all contributers. The copyright of the package could then just list DarkWyrm as original author, and "The HaikuArchives Contributers" summarily.
I propose to do it like this for all apps, saves copyright lists for packages getting longer and longer over time, which nobody sees anyway, because HaikuDepot list only the first 2(?).
